### ISSUE TITLE
Expanding a graph of language and automaticaly recognizing the same name recurrence, is it possible ?

### ISSUE THREAD

**Issue by Uiuran** [Technologicat/pydialect#1]
"Due to the potentially unlimited complexity of interactions between language features defined by different dialects, there is by design no automation for combining dialects. In the general case, this is something that requires human intervention. "

Did you think the question i just made in the title is improbable or impossible ? iam interested in this, see that is important to expand artificial intelligence computer graphs languages to an automaticaly nameable architectonic computer language (similar to what is done with ASTs and in pyan).
By example see this feature request in tensorflow:

https://github.com/tensorflow/tensorflow/issues/30991

**Comment by Technologicat** [comment]
I'm sorry, I don't understand the question. I looked at the tensorflow feature request, but it didn't help much. I suppose I'm missing the required context.

Do you mean automatically avoiding some sort of naming conflicts?

If not, could you explain the question in more detail, or are there more examples?

**Comment by Uiuran** [comment]
yes,also automaticly recognize functional structures of graph, idepedently
of any parametric numerical value




Em qui, 25 de jul de 2019 19:40, Juha Jeronen <notifications@github.com>
escreveu:
